# Generated by Django 3.2.5 on 2021-07-13 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0003_prefixsuffixprediction_predictions'),
    ]

    operations = [
        migrations.AddField(
            model_name='prefixsuffixprediction',
            name='type',
            field=models.CharField(default='unknown', max_length=200),
        ),
    ]
