# Generated by Django 3.2.5 on 2021-07-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0005_auto_20210713_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='slug',
            field=models.SlugField(blank=True, max_length=300),
        ),
    ]
